models:
  xtts_base_model: "tts_models/multilingual/multi-dataset/xtts_v2"
  xtts_vietnamese: "capleaf/viXTTS"
  indic_model: "ai4bharat/indic-parler-tts-pretrained"

kokoro_speed: 1

directories:
  audio_output_dir: "/app/src/audio"
  vietnamese_model_dir: "vn_model"

paths:
  key_path: "/app/src/certificates/_.klassifier.com.key"
  cert_path: "/app/src/certificates/combined_certificate.crt"
  google_credentials: "/app/src/certificates/klassifier-translation-322b40f8ffce.json"

flask:
  port: 5000
  host: "0.0.0.0"

reference_audio_paths:
  male: "/app/src/references/male.mp3"
  female: "/app/src/references/female.mp3"

cleanup:
  max_age_hours: 0.167 # delete any audio older than 10 minutes (10/60 = 0.167 hours)
  min_free_space_mb: 1000 # if memory is lower than # mb, delete any audio
  cleanup_interval_minutes: 2 # run every # min
