POLLY_SAMPLE_RATE = 16000
POLLY_LANGUAGE_NAMES = {
    'arb': 'Polly Arabic',
    'ar-AE': 'Polly Arabic (Gulf)',
    'ca-ES': 'Polly Catalan',
    'yue-CN': 'Polly Chinese (Cantonese)',
    'cmn-CN': 'Polly Chinese (Mandarin)',
    'cs-CZ': 'Polly Czech',
    'da-DK': 'Polly Danish',
    'nl-BE': 'Polly Dutch (Belgian)',
    'nl-NL': 'Polly Dutch',
    'en-AU': 'Polly English (Australian)',
    'en-GB': 'Polly English (British)',
    'en-IN': 'Polly English (Indian)',
    'en-NZ': 'Polly English (New Zealand)',
    'en-ZA': 'Polly English (South African)',
    'en-US': 'Polly English (US)',
    'en-GB-WLS': 'Polly English (Welsh)',
    'fi-FI': 'Polly Finnish',
    'fr-FR': 'Polly French',
    'fr-BE': 'Polly French (Belgian)',
    'fr-CA': 'Polly French (Canadian)',
    'hi-IN': 'Polly Hindi',
    'de-DE': 'Polly German',
    'de-AT': 'Polly German (Austrian)',
    'de-CH': 'Polly German (Swiss standard)',
    'is-IS': 'Polly Icelandic',
    'it-IT': 'Polly Italian',
    'ja-JP': 'Polly Japanese',
    'ko-KR': 'Polly Korean',
    'nb-NO': 'Polly Norwegian',
    'pl-PL': 'Polly Polish',
    'pt-BR': 'Polly Portuguese (Brazilian)',
    'pt-PT': 'Polly Portuguese (European)',
    'ro-RO': 'Polly Romanian',
    'ru-RU': 'Polly Russian',
    'es-ES': 'Polly Spanish (Spain)',
    'es-MX': 'Polly Spanish (Mexican)',
    'es-US': 'Polly Spanish (US)',
    'sv-SE': 'Polly Swedish',
    'tr-TR': 'Polly Turkish',
    'cy-GB': 'Polly Welsh'
}

XTTS_SAMPLE_RATE = 24000
XTTS_LANGUAGE_NAMES = {
    "en": "English",
    "sp": "Spanish",
    "fr": "French",
    "de": "German",
    "it": "Italian",
    "pt": "Portuguese",
    "pl": "Polish",
    "tr": "Turkish",
    "ru": "Russian",
    "nl": "Dutch",
    "cs": "Czech",
    "ar": "Arabic",
    "zh-cn": "Chinese",
    "ja": "Japanese",
    "hu": "Hungarian",
    "ko": "Korean",
    "hi": "Hindi"    
}

KOKORO_VOICE_CHOICES = [
    ("KOKORO US Default Female (af)", "af", "f"),
    ("KOKORO US Bella", "af_bella", "f"),
    ("KOKORO US Sarah", "af_sarah", "f"),
    ("KOKORO US Nicole", "af_nicole", "f"),
    ("KOKORO US Sky", "af_sky", "f"),
    ("KOKORO US Michael", "am_michael", "m"),
    ("KOKORO US Adam", "am_adam", "m"),
    ("KOKORO GB Emma", "bf_emma", "f"),
    ("KOKORO GB Isabella", "bf_isabella", "f"),
    ("KOKORO GB George", "bm_george", "m"),
    ("KOKORO GB Lewis", "bm_lewis", "m")
]

INDIC_VOICES = {
    "Assamese": [("Amit", "Male"), ("Site", "Female")],
    "Bengali": [("Arjun", "Male"), ("Aditi", "Female")],
    "Bodo": [("Bikram", "Male"), ("Maya", "Female")],
    "Chhattisgarhi": [("Bhanu", "Male"), ("Champa", "Female")],
    "Dogri": [("Karan", "Male")],
    "Gujarati": [("Yash", "Male"), ("Neha", "Female")],
    "Hindi": [("Rohit", "Male"), ("Divya", "Female")],
    "Kannada": [("Suresh", "Male"), ("Anu", "Female")],
    "Malayalam": [("Harish", "Male"), ("Anjali", "Female")],
    "Manipuri": [("Laishram", "Male"), ("Ranjit", "Male")],
    "Marathi": [("Sanjay", "Male"), ("Sunita", "Female")],
    "Nepali": [("Amrita", "Female")],
    "Odia": [("Manas", "Male"), ("Debjani", "Female")],
    "Punjabi": [("Divjot", "Male"), ("Gurpeet", "Female")],
    "Sanskrit": [("Aryan", "Male")],
    "Tamil": [("Jaya", "Female")],
    "Telugu": [("Prakash", "Male"), ("Lalitha", "Female")]
}

INDIC_LANG_CODES = {
    "Assamese": "as",
    "Bengali": "bn",
    "Bodo": "brx",
    "Chhattisgarhi": "hne",
    "Dogri": "doi",
    "Gujarati": "gu",
    "Hindi": "hi",
    "Kannada": "kn",
    "Malayalam": "ml",
    "Manipuri": "mni",
    "Marathi": "mr",
    "Nepali": "ne",
    "Odia": "or",
    "Punjabi": "pa",
    "Sanskrit": "sa",
    "Tamil": "ta",
    "Telugu": "te"
}